/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResultRouteImport } from './routes/result'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as Mp3RouteImport } from './routes/mp3'
import { Route as HowToRouteImport } from './routes/how-to'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDownloadRouteImport } from './routes/api/download'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const Mp3Route = Mp3RouteImport.update({
  id: '/mp3',
  path: '/mp3',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToRoute = HowToRouteImport.update({
  id: '/how-to',
  path: '/how-to',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadRoute = ApiDownloadRouteImport.update({
  id: '/api/download',
  path: '/api/download',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/how-to': typeof HowToRoute
  '/mp3': typeof Mp3Route
  '/photos': typeof PhotosRoute
  '/privacy': typeof PrivacyRoute
  '/result': typeof ResultRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/api/download': typeof ApiDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/how-to': typeof HowToRoute
  '/mp3': typeof Mp3Route
  '/photos': typeof PhotosRoute
  '/privacy': typeof PrivacyRoute
  '/result': typeof ResultRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/api/download': typeof ApiDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/how-to': typeof HowToRoute
  '/mp3': typeof Mp3Route
  '/photos': typeof PhotosRoute
  '/privacy': typeof PrivacyRoute
  '/result': typeof ResultRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/api/download': typeof ApiDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/cookies'
    | '/how-to'
    | '/mp3'
    | '/photos'
    | '/privacy'
    | '/result'
    | '/sitemap.xml'
    | '/stories'
    | '/terms'
    | '/api/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/cookies'
    | '/how-to'
    | '/mp3'
    | '/photos'
    | '/privacy'
    | '/result'
    | '/sitemap.xml'
    | '/stories'
    | '/terms'
    | '/api/download'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/cookies'
    | '/how-to'
    | '/mp3'
    | '/photos'
    | '/privacy'
    | '/result'
    | '/sitemap.xml'
    | '/stories'
    | '/terms'
    | '/api/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  HowToRoute: typeof HowToRoute
  Mp3Route: typeof Mp3Route
  PhotosRoute: typeof PhotosRoute
  PrivacyRoute: typeof PrivacyRoute
  ResultRoute: typeof ResultRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRoute
  TermsRoute: typeof TermsRoute
  ApiDownloadRoute: typeof ApiDownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mp3': {
      id: '/mp3'
      path: '/mp3'
      fullPath: '/mp3'
      preLoaderRoute: typeof Mp3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to': {
      id: '/how-to'
      path: '/how-to'
      fullPath: '/how-to'
      preLoaderRoute: typeof HowToRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download': {
      id: '/api/download'
      path: '/api/download'
      fullPath: '/api/download'
      preLoaderRoute: typeof ApiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  HowToRoute: HowToRoute,
  Mp3Route: Mp3Route,
  PhotosRoute: PhotosRoute,
  PrivacyRoute: PrivacyRoute,
  ResultRoute: ResultRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRoute,
  TermsRoute: TermsRoute,
  ApiDownloadRoute: ApiDownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
